"""LoRA sweep visualization — rank vs accuracy curves for modern_test, cf, eval.

Reads results/lora_sweep.csv (already generated by the sweep). Produces
figures/fig5_lora_sweep.png with M1b accuracy and AUROC across rank/epoch configs.

Usage:
  python scripts/fig_lora_sweep.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src import config


def main() -> int:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    csv_path = config.RESULTS_DIR / "lora_sweep.csv"
    if not csv_path.exists():
        print(f"[sweep-fig] ERROR: {csv_path} not found. Run the sweep first.")
        return 1

    df = pd.read_csv(csv_path)
    m1b = df[df["model"] == "M1b"].copy()
    m1a = df[df["model"] == "M1a"].copy()

    splits = ["modern_test", "cf", "eval"]
    split_labels = {
        "modern_test": "modern_test (in-generator)",
        "cf": "Community Forensics (cross-generator)",
        "eval": "Full eval",
    }
    epoch_styles = {5: ("o", "-"), 10: ("s", "--")}

    fig, axes = plt.subplots(1, 3, figsize=(15, 4.5), sharey=False)

    for ax, split in zip(axes, splits):
        sub = m1b[m1b["split"] == split]
        # M1a baseline (frozen, same across ranks) — take mean across configs
        baseline_acc = m1a[m1a["split"] == split]["acc"].mean()
        baseline_auroc = m1a[m1a["split"] == split]["auroc"].mean()

        for ep, (marker, ls) in epoch_styles.items():
            ep_data = sub[sub["epochs"] == ep].sort_values("r")
            if ep_data.empty:
                continue
            ax.plot(ep_data["r"], ep_data["acc"], marker=marker, ls=ls,
                    color="tab:blue", label=f"M1b acc (ep={ep})")
            ax.plot(ep_data["r"], ep_data["auroc"], marker=marker, ls=ls,
                    color="tab:orange", label=f"M1b AUROC (ep={ep})")

        ax.axhline(baseline_acc, ls=":", color="tab:blue", alpha=0.5, label="M1a acc")
        ax.axhline(baseline_auroc, ls=":", color="tab:orange", alpha=0.5, label="M1a AUROC")
        ax.set_xlabel("LoRA rank")
        ax.set_title(split_labels[split], fontsize=10)
        ax.set_xticks([4, 8, 16, 32])

    axes[0].set_ylabel("Score")
    # single legend for the figure
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=3, fontsize=8,
               bbox_to_anchor=(0.5, -0.02))
    fig.suptitle("Figure 5 — LoRA hyperparameter sweep: rank vs performance (alpha = 2 x rank)",
                 fontsize=12)
    fig.tight_layout(rect=(0, 0.08, 1, 0.95))

    config.FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    out_path = config.FIGURES_DIR / "fig5_lora_sweep.png"
    fig.savefig(out_path, dpi=150, bbox_inches="tight")
    print(f"[sweep-fig] saved -> {out_path}")

    # print summary table
    print("\n[sweep-fig] M1b accuracy by config:")
    piv = m1b.pivot_table(index=["r", "alpha", "epochs"], columns="split",
                          values="acc").round(3)
    print(piv[splits].to_string())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
